CREATE INDEX "certificates_trail_id_idx" ON "certificates" USING btree ("trail_id");--> statement-breakpoint
CREATE INDEX "challenge_submissions_user_id_idx" ON "challenge_submissions" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "challenge_submissions_challenge_id_idx" ON "challenge_submissions" USING btree ("challenge_id");--> statement-breakpoint
CREATE INDEX "challenge_tests_challenge_id_idx" ON "challenge_tests" USING btree ("challenge_id");--> statement-breakpoint
CREATE INDEX "community_comments_post_id_idx" ON "community_comments" USING btree ("post_id");--> statement-breakpoint
CREATE INDEX "community_comments_user_id_idx" ON "community_comments" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "community_likes_user_id_idx" ON "community_likes" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "community_posts_user_id_idx" ON "community_posts" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "comunicado_respostas_user_id_idx" ON "comunicado_respostas" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "lessons_progress_lesson_id_idx" ON "lessons_progress" USING btree ("lesson_id");--> statement-breakpoint
CREATE INDEX "lessons_trail_id_idx" ON "lessons" USING btree ("trail_id");--> statement-breakpoint
CREATE INDEX "lessons_module_id_idx" ON "lessons" USING btree ("module_id");--> statement-breakpoint
CREATE INDEX "modules_trail_id_idx" ON "modules" USING btree ("trail_id");--> statement-breakpoint
CREATE INDEX "oauth_accounts_user_id_idx" ON "oauth_accounts" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "question_answers_question_id_idx" ON "question_answers" USING btree ("question_id");--> statement-breakpoint
CREATE INDEX "question_answers_selected_option_id_idx" ON "question_answers" USING btree ("selected_option_id");--> statement-breakpoint
CREATE INDEX "question_options_question_id_idx" ON "question_options" USING btree ("question_id");--> statement-breakpoint
CREATE INDEX "questions_lesson_id_idx" ON "questions" USING btree ("lesson_id");--> statement-breakpoint
CREATE INDEX "roadmap_stage_completions_stage_id_idx" ON "roadmap_stage_completions" USING btree ("stage_id");--> statement-breakpoint
CREATE INDEX "roadmap_stage_refs_stage_id_idx" ON "roadmap_stage_refs" USING btree ("stage_id");--> statement-breakpoint
CREATE INDEX "roadmap_stages_roadmap_id_idx" ON "roadmap_stages" USING btree ("roadmap_id");--> statement-breakpoint
CREATE INDEX "simulado_attempt_answers_question_id_idx" ON "simulado_attempt_answers" USING btree ("question_id");--> statement-breakpoint
CREATE INDEX "simulado_attempt_answers_option_id_idx" ON "simulado_attempt_answers" USING btree ("option_id");--> statement-breakpoint
CREATE INDEX "simulado_attempt_questions_question_id_idx" ON "simulado_attempt_questions" USING btree ("question_id");--> statement-breakpoint
CREATE INDEX "simulado_attempts_user_id_idx" ON "simulado_attempts" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "simulado_attempts_simulado_id_idx" ON "simulado_attempts" USING btree ("simulado_id");--> statement-breakpoint
CREATE INDEX "simulado_options_question_id_idx" ON "simulado_options" USING btree ("question_id");--> statement-breakpoint
CREATE INDEX "simulado_questions_simulado_id_idx" ON "simulado_questions" USING btree ("simulado_id");--> statement-breakpoint
CREATE INDEX "subscriptions_user_id_idx" ON "subscriptions" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "tokens_user_id_idx" ON "tokens" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "trail_reviews_trail_id_idx" ON "trail_reviews" USING btree ("trail_id");--> statement-breakpoint
CREATE INDEX "trail_tags_tag_id_idx" ON "trail_tags" USING btree ("tag_id");--> statement-breakpoint
CREATE INDEX "user_achievements_achievement_id_idx" ON "user_achievements" USING btree ("achievement_id");--> statement-breakpoint
CREATE INDEX "user_follows_following_id_idx" ON "user_follows" USING btree ("following_id");